# ruff: noqa: E501
"""create_number_tables

Revision ID: 00bb85eb4919
Revises: 
Create Date: 2026-07-11 09:43:17.594675

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '00bb85eb4919'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('number_categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_number_categories'))
    )
    op.create_index(op.f('idx_number_categories_name'), 'number_categories', ['name'], unique=True)
    op.create_table('number_sources',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_number_sources'))
    )
    op.create_index(op.f('idx_number_sources_name'), 'number_sources', ['name'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=True)
    op.create_table('number_records',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['number_categories.id'], name=op.f('fk_number_records_number_categories')),
    sa.ForeignKeyConstraint(['source_id'], ['number_sources.id'], name=op.f('fk_number_records_number_sources')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_number_records_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_number_records'))
    )
    op.create_index(op.f('idx_number_records_number'), 'number_records', ['number'], unique=False)
    op.create_index(op.f('idx_number_records_recorded_at'), 'number_records', ['recorded_at'], unique=False)
    op.create_index(op.f('idx_number_records_user_id'), 'number_records', ['user_id'], unique=False)
    op.create_table('number_tags',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_number_tags_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_number_tags')),
    sa.UniqueConstraint('user_id', 'name', name='uq_number_tags_user_id_name')
    )
    op.create_index(op.f('idx_number_tags_name'), 'number_tags', ['name'], unique=False)
    op.create_index(op.f('idx_number_tags_user_id'), 'number_tags', ['user_id'], unique=False)
    op.create_table('record_tags',
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['number_records.id'], name=op.f('fk_record_tags_number_records'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['number_tags.id'], name=op.f('fk_record_tags_number_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id', 'tag_id', name=op.f('pk_record_tags'))
    )
    # ### end Alembic commands ###

    # Seeding lookup tables
    import uuid
    from datetime import UTC, datetime

    sources_table = sa.sql.table(
        'number_sources',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    )
    op.bulk_insert(sources_table, [
        {
            "id": uuid.uuid4(),
            "name": "Car Plate",
            "description": "Vehicle license plate number",
            "created_at": datetime.now(UTC),
            "updated_at": datetime.now(UTC),
        },
        {
            "id": uuid.uuid4(),
            "name": "Phone",
            "description": "Telephone number",
            "created_at": datetime.now(UTC),
            "updated_at": datetime.now(UTC),
        },
        {
            "id": uuid.uuid4(),
            "name": "House Number",
            "description": "House or building number",
            "created_at": datetime.now(UTC),
            "updated_at": datetime.now(UTC),
        },
        {
            "id": uuid.uuid4(),
            "name": "Dream",
            "description": "Numbers observed in a dream",
            "created_at": datetime.now(UTC),
            "updated_at": datetime.now(UTC),
        },
        {
            "id": uuid.uuid4(),
            "name": "Receipt",
            "description": "Transaction receipt numbers",
            "created_at": datetime.now(UTC),
            "updated_at": datetime.now(UTC),
        },
        {
            "id": uuid.uuid4(),
            "name": "Random",
            "description": "Random number observation",
            "created_at": datetime.now(UTC),
            "updated_at": datetime.now(UTC),
        },
    ])

    categories_table = sa.sql.table(
        'number_categories',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    )
    op.bulk_insert(categories_table, [
        {
            "id": uuid.uuid4(),
            "name": "Lucky",
            "description": "Personal lucky number",
            "created_at": datetime.now(UTC),
            "updated_at": datetime.now(UTC),
        },
        {
            "id": uuid.uuid4(),
            "name": "Daily",
            "description": "Daily number",
            "created_at": datetime.now(UTC),
            "updated_at": datetime.now(UTC),
        },
        {
            "id": uuid.uuid4(),
            "name": "Lottery",
            "description": "Lottery game number",
            "created_at": datetime.now(UTC),
            "updated_at": datetime.now(UTC),
        },
        {
            "id": uuid.uuid4(),
            "name": "Observation",
            "description": "Observation from environment",
            "created_at": datetime.now(UTC),
            "updated_at": datetime.now(UTC),
        },
        {
            "id": uuid.uuid4(),
            "name": "Other",
            "description": "Other category",
            "created_at": datetime.now(UTC),
            "updated_at": datetime.now(UTC),
        },
    ])



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record_tags')
    op.drop_index(op.f('idx_number_tags_user_id'), table_name='number_tags')
    op.drop_index(op.f('idx_number_tags_name'), table_name='number_tags')
    op.drop_table('number_tags')
    op.drop_index(op.f('idx_number_records_user_id'), table_name='number_records')
    op.drop_index(op.f('idx_number_records_recorded_at'), table_name='number_records')
    op.drop_index(op.f('idx_number_records_number'), table_name='number_records')
    op.drop_table('number_records')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('idx_number_sources_name'), table_name='number_sources')
    op.drop_table('number_sources')
    op.drop_index(op.f('idx_number_categories_name'), table_name='number_categories')
    op.drop_table('number_categories')
    # ### end Alembic commands ###
