"""Alembic migration environment.

The database connection URL is loaded from the application's settings
(which in turn reads the DATABASE_URL environment variable) rather than
being hardcoded in alembic.ini. No migrations are generated by this task;
this only wires up the migration environment for future use.
"""

from logging.config import fileConfig

from sqlalchemy import engine_from_config, pool

from alembic import context
from app.core.config import get_settings
from app.core.database import Base
from app.core.logging import configure_logging, get_logger

# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config

# Interpret the config file for Python logging.
# This line sets up loggers basically.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

configure_logging()
logger = get_logger("alembic.env")

# Load the database URL from application settings (DATABASE_URL env var)
# instead of hardcoding it in alembic.ini.
settings = get_settings()
config.set_main_option("sqlalchemy.url", settings.DATABASE_URL)

# SQLAlchemy metadata used for autogenerate support. No models are defined
# yet, so this currently points at an empty metadata object.
target_metadata = Base.metadata


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    This configures the context with just a URL and not an Engine, though
    an Engine is acceptable here as well. By skipping the Engine creation
    we don't even need a DBAPI to be available.

    Calls to context.execute() here emit the given string to the script
    output.
    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    logger.info("Migration started (offline mode)")
    with context.begin_transaction():
        context.run_migrations()
    logger.info("Migration completed (offline mode)")


def run_migrations_online() -> None:
    """Run migrations in 'online' mode.

    In this scenario we need to create an Engine and associate a
    connection with the context.
    """
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    logger.info("Migration started (online mode)")
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)

        with context.begin_transaction():
            context.run_migrations()
    logger.info("Migration completed (online mode)")


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
